### DISCUSSION TITLE
Adding Source Information to Responses

### DISCUSSION THREAD

**Discussion by asafieva** [CBIIT/ccdi-federation-api#62] [API Design Discussion]
Federation Aggregation layer would like to keep each Federation space results aggregated but as separate entities received from federation spaces.

We need to add "**_source_**" response entity attributes identifying federated members sending responses. 

The new attribute name can be any we select, say from "[_source|originator|owner|origin|space_]" with fixed values currently from the set [_"UChicago"|"StJude"|"UCSC"|"CHOP"_]. We shall select an attribute name. The values are federation members' choice, but shall be unique across the federation.

When one entity is returned based on a _namespace_ and an _ID_, we does not look like need that source attribute.

I suggest this attribute is added to the swagger specification response entities as _required_ for federation members to add it to the responses. If this suggestion is not upvoted, the attribute shall be added in the aggregation layer.

I think it would be more clear for future users if every federated response returned this owner information besides the responses to retrieve by IDs, where having explicit namespaces looks enough for one returned entity.

Here is one example of how an aggregated response would look with the new attribute added and the results compiled into an array of responses, an endpoint "_api/v0/subject/by/race/count_".
```yaml
[
    {
        "source": "CHOP",
        "total": 0,
        "values": {}
    },
    {
        "source": "UChicago",
        "total": 22328,
        "values": {
            "White": 16214,
            "Unknown": 2481,
            "Black or African American": 2434,
            "Asian": 690,
            "Not Reported": 288,
            "American Indian or Alaska Native": 104,
            "Native Hawaiian or Other Pacific Islander": 60,
            "Multiracial": 57
        }
    },
    {
        "source": "UCSC",
        "total": 128,
        "values": {
            "Unknown": 107,
            "Not Reported,White": 1,
            "White": 13,
            "Not Reported": 5,
            "Asian": 2
        }
    },
    {
        "source": "StJude",
        "total": 13591,
        "values": {
            "White": 8303,
            "Not Reported": 2975,
            "Asian": 82,
            "Black or African American": 2059,
            "missing": 145,
            "Native Hawaiian or other Pacific Islander": 3,
            "American Indian or Alaska Native": 22,
            "Unknown": 2
        }
    }
]
```
